services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: PORT
        value: 5678
      - key: NODE_FUNCTION_ALLOW_EXTERNAL
        value: puppeteer
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 10
